# ═══════════════════════════════════════════════════════════
# AUTH SERVICE — Perfil de Desenvolvimento
# Ativo com: spring.profiles.active=dev
# ═══════════════════════════════════════════════════════════

server.port=8081

# ── Banco de dados ── valores fixos para dev local
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ── JWT ── chaves fixas para dev local
jwt.private-key=-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCZfPfT4g5aMNn12WZrwOqn5Yab4aX+qC+Xp3gfFMY9Rutajd9plgec5iyi0V962IROjHqgciOqyzDBXNH34lS70aPdLTUpG1r9iJ6st7WIdZuuPajnZknYFk9B8387qPHVQkRJ1yAYhQp7vxNAMlA4FB/2YcwYflTrYAdepO+l3K+ACHAusIenpGN1YviSD7gaetH4hSDdDy4KMMPcGrbDbug8xfMi9Xm0Foh0xCTHdnKuo4oa/UEOu+FNb+A/4B7cd5yJV2LC1wrDLo8zJV+Wlv2KVosv7gkcvvyUU2CxaexoiyfEk2UA6FCLTnt+QKLU4KHJPGnDjcaX4OKThzQDAgMBAAECggEADvwlZ0P1qhaE4RIVhBr0jenEZ5RIftaatuVRvpm/n5yR6RMFfIB6Q8uGZhWniw3NH6zADXQMnrscX8nDx2i1ub8w5AIVjkAudPw79EQx7p2qJ6u7bBlkx4+os0P7kwPegGHqMC9W4did+mY1ke9CPQdcoNL8IxQKZGR0CRMfQS5mCwZ0JVj+5gPW8satWcc+3gn4jqCWEfp8YNFFKwbLKwxDHBcrQZOgKi0n5aHAbg6YJkAUyLJDbfh4+Vsdzzua8E3Yqm9cFQnW3IxbR7CDwWPqoGH6lTdJdWehJBT/aYlCO6w7PPdB8/PNDY41j//LmXKtvu8h4s3ADcF/ylYcMQKBgQDVZU63xxRhKSyN6lB9qG+Or+PCVwrpFKAZgcQzkXMGephNWAbGN0kZ8ogcU6CqyquCJDuVaBVCGQi7x9VrZB6K8rFlhSMavqTi1GPNVJCaRhG18ibtQD+4kSO6oGz4O67WO1p+LJQ+Vo5niu72R/7/7vi6UzLdgtPWuwGXlUstuQKBgQC4IcYriTaKbSCc52QmT/Y2MepFsAWqk7D2jY86AQK+mewVl2U+rpvcLt2FIZDqduPl2cp1y3GuGklcefTp1bzuAcaaVnOHylgQLYGcni+X4Tz0GBajcyx3mDFhreBR7Q4XPweMdVCCQRSO/YxvGsFCSjNsN8JgZADeKG4HPEEtmwKBgHdq+RFJPDNfOkq0vJSFZOCBt8Byu21SGIINp4GAPNF8W6y0vR3BpIv7uIW5mujY//+VTS7AD11s6wFCxEETxy/UvsdkKQ/3bght+OfYEg/zdEfQmk4crUwZFNiEnFaR97Z1gp+nTNJR1+FD05RJF/+beN+0XXuukePRxQNSDb8pAoGACxp+SMHNeCt8e/m4IFdSEZKQ/gLPVKnzUerXaDgHYlcF1Yd7o3wEChMJaK3Nf1YMCCBKBTBveoA7TEhObItnCTMyNrxf2yBojxEvb7JaTF5Yvp91PgYD+HJFCA7kKAyTfPNgEShB4pjqFHVVsp16afTvhOcX4ZgmNT9a4zTO+WECgYApf2WDnqSNycRc7rjzKwOPHSaU6wD8ROmrz1c+SsTgwFmNvSJz/Vl19S7BNCSRncFIJozHPEUuLEPezdcM/EO8an0/6Seq63uK2Yh291gthApXQukw0iblb2RH140cP6pDrRlzvWYpzoMKJm/BrnWYXVExd7k6yvU1dVgf7k+v4g==\n-----END PRIVATE KEY-----

jwt.public-key=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmXz30+IOWjDZ9dlma8Dqp+WGm+Gl/qgvl6d4HxTGPUbrWo3faZYHnOYsotFfetiETox6oHIjqsswwVzR9+JUu9Gj3S01KRta/YierLe1iHWbrj2o52ZJ2BZPQfN/O6jx1UJESdcgGIUKe78TQDJQOBQf9mHMGH5U62AHXqTvpdyvgAhwLrCHp6RjdWL4kg+4GnrR+IUg3Q8uCjDD3Bq2w27oPMXzIvV5tBaIdMQkx3ZyrqOKGv1BDrvhTW/gP+Ae3HeciVdiwtcKwy6PMyVflpb9ilaLL+4JHL78lFNgsWnsaIsnxJNlAOhQi057fkCi1OChyTxpw43Gl+Dik4c0AwIDAQAB\n-----END PUBLIC KEY-----

jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ── Eureka ──
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ── Logs ──
logging.level.com.tribunalbank=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ── Swagger ──
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Log temporário para debugar
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG