spring.application.name=api-gateway

# Profile ativo
spring.profiles.active=dev

server.port=8080

# Registra o gateway no Eureka para que ele apareça no dashboard
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Habilita o roteamento automático via nome dos serviços registrados no Eureka
spring.cloud.gateway.server.webmvc.discovery.locator.enabled=true

# Converte o nome dos serviços para minúsculo na URL
# Exemplo: acessa /auth-service/** em vez de /AUTH-SERVICE/**
spring.cloud.gateway.server.webmvc.discovery.locator.lower-case-service-id=true