spring.application.name=discovery-server
server.port=8761


# Impede que o próprio servidor Eureka tente se registrar nele mesmo como cliente
# Sem isso ele entra em loop tentando se registrar em si próprio
eureka.client.register-with-eureka=false

# Impede que o servidor tente buscar a lista de serviços registrados em outro Eureka
eureka.client.fetch-registry=false

# Profile ativo
spring.profiles.active=dev