server.port=8083

# ── Banco de dados ──────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5435/conta_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ── JPA ─────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# ── Flyway ──────────────────────────────────────────
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ── JWT — chave pública do Auth Service ─────────────
# Apenas verificação — conta-service nunca gera tokens
jwt.public-key=-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmXz30+IOWjDZ9dlma8Dqp+WGm+Gl/qgvl6d4HxTGPUbrWo3faZYHnOYsotFfetiETox6oHIjqsswwVzR9+JUu9Gj3S01KRta/YierLe1iHWbrj2o52ZJ2BZPQfN/O6jx1UJESdcgGIUKe78TQDJQOBQf9mHMGH5U62AHXqTvpdyvgAhwLrCHp6RjdWL4kg+4GnrR+IUg3Q8uCjDD3Bq2w27oPMXzIvV5tBaIdMQkx3ZyrqOKGv1BDrvhTW/gP+Ae3HeciVdiwtcKwy6PMyVflpb9ilaLL+4JHL78lFNgsWnsaIsnxJNlAOhQi057fkCi1OChyTxpw43Gl+Dik4c0AwIDAQAB\n-----END PUBLIC KEY-----

# ── Eureka ───────────────────────────────────────────
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ── Actuator ─────────────────────────────────────────
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ── Swagger ──────────────────────────────────────────
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ── FeignClient ──────────────────────────────────────
# Timeout para chamadas ao Cliente Service
# connect-timeout → tempo máximo para estabelecer conexão (ms)
# read-timeout    → tempo máximo para receber a resposta (ms)
spring.cloud.openfeign.client.config.cliente-service.connect-timeout=3000
spring.cloud.openfeign.client.config.cliente-service.read-timeout=5000

# Log das chamadas Feign — FULL em dev para ver body completo
# Em produção mudar para BASIC ou NONE
logging.level.com.tribunalbank.conta.client=DEBUG

# ── Logs ─────────────────────────────────────────────
logging.level.com.tribunalbank=DEBUG
logging.level.org.hibernate.SQL=DEBUG